#!/bin/sh
#
# profilerc
# Referenced by ENV in dash, ksh, bash --posix, yash -o posix, mksh etc.

test "${-##*i*}" = "$-" || {
	rc=;
	cmd=$(/usr/bin/env /usr/bin/which "$(/usr/bin/basename "$(/bin/readlink -f "$0")")");

	case $cmd in
		(/bin/mksh)
			case $KSH_VERSION in
				(*MIRBSD\ KSH*)
					rc=$HOME/.mkshrc;;
			esac;;
		(/usr/bin/ksh)
			case $KSH_VERSION in
				(*AJM*|Version\ A*)
					rc=$HOME/.kshrc;;
			esac;;
		(/bin/bash|/bin/dash|/usr/bin/yash)
			rc=$HOME/.dashrc;;
	esac;

	if
		test -n "$rc" -a -e "$rc";
	then
		. "$rc";
		export POSIXLY_CORRECT;
		POSIXLY_CORRECT=y;
		SHELL=$cmd;
	fi;

	unset -v rc cmd;
};

# vim: set ft=sh :
