#!/bin/sh
#
# profilerc
# Referenced by ENV in dash, ksh, bash --posix, yash -o posix, mksh etc.

test "${-##*i*}" = "$-" || {
	rc=;
	cmd=$(/usr/bin/env /usr/bin/which "$(/usr/bin/basename "$(/bin/readlink -f "$0")")");
	HOME=${HOME:-/home/$(/usr/bin/id -un)};

	case $cmd in
		(/bin/mksh)
			case $KSH_VERSION in
				(*MIRBSD\ KSH*)
					rc=$HOME/.mkshrc;;
			esac;;
		(/usr/bin/ksh)
			case $KSH_VERSION in
				(*AJM*|Version\ A*)
					rc=$HOME/.kshrc;;
			esac;;
		(/bin/bash|/bin/dash|/usr/bin/yash)
			export POSIXLY_CORRECT;
			POSIXLY_CORRECT=y;
			rc=$HOME/.dashrc;;
	esac;

	test -r "$rc" && {
		. "$rc";
		SHELL=$cmd;
	};

	unset -v rc cmd;
};

# vim: set ft=sh :
